apiVersion: v1
kind: Service
metadata:
  name: student-visor-frontend-service
  namespace: studentvisor
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer