version: "3"
services:
  node-service:
    build:
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MASTER_SECRET=${MASTER_SECRET}
    command: npm start
  pyflask-service:
    #DEBUG_MODE environment variable is REQUIRED
    #The server opens up in production mode if the DEBUG_MODE environment variable is set to False
    environment:
      - PYFLASK_ENV=production
      - DEBUG_MODE=False
    command:
      gunicorn -w 4 -b 0.0.0.0:5100 app:app #Host 0.0.0.0 means that the server can be accessed by anyone, but only if the container opens a port
      #In this case we dont want this, so we dont open any port
      #-w 4 means 4 working processes to process tasks concurrently, at the expense of resources and possible race conditions (e.g. opening and manipulating files)

  mongo-service:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
