apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: studentvisor
spec:
  selector:
    app: node-service
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer #Check if node port is better here