apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: studentvisor
spec:
  selector:
    app: node
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP #Check if node port is better here