apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-pyflask-shared-volume
  namespace: studentvisor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi