# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-volume
  namespace: studentvisor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-pyflask-shared-volume
  namespace: studentvisor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi